language: php

php:
  - 7.4
  - 8.0
  - 8.1

env:
  - COMPOSER_FLAGS="--prefer-source --no-interaction"
  - COVERAGE=true
  - PHPSPEC_FLAGS="--config phpspec.yml.ci"

install:
  - travis_retry composer update ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpspec run ${PHPSPEC_FLAGS}

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
